### ISSUE TITLE
[BUG] Sudden stop with no creation of images

### ISSUE THREAD

**Issue by Dev252323** [bedrock-viz/bedrock-viz#134] opened 2021-10-28 20:07 UTC
I have a realm which has been going for over 2 years.
2 months ago I have found and used Bedrock viz on a backup of the world (_Incredible tool btw_), but yesterday I decided make an up to date map on a new backup of a more current version of the world but the map was not generated.

**Describe the bug**
The process stopped suddenly and only the log was created

**To Reproduce**
On cmd used the following command: `bedrock-viz.exe --db path-to-my-world-file-dir/ --out out4 --html-most`(used out4 for archiving purposes)
Have tried using html most, all, and simple.

**Screenshots**
Screenshot of the cmd after fail:
![image](https://user-images.githubusercontent.com/89285135/139325920-d84e3072-09d7-488b-a382-ff8ccece8219.png)

The only archive generated:
[bedrock_viz.log](https://github.com/bedrock-viz/bedrock-viz/files/7437019/bedrock_viz.log)

**Environment Information:**
 - OS: Windows 10
 - bedrock-viz version: bedrock-viz_v0.1.4_win64 

**As always thanks for the support and the incredible tool you have created.**

**Comment by Dev252323** [comment] 2021-11-03 03:14
I could not tell you. But I believe I can provide a copy of the world. 

https://drive.google.com/drive/folders/1EUxoNSCirLNTOPC2swcc1HxRlK6VCT3q?usp=sharing

please update me in any new information, again thanks for the help.

**Comment by Desterly** [comment] 2021-11-03 13:25
Thanks.  Looking at it now.   

I see the cause of the crash but..... there's some odd things in this world I want to look at before posting.

Based on the name, this world is running in a realm?

**Comment by Dev252323** [comment] 2021-11-03 18:58
Yes the world I sent you is a copy of a realm.

The map is 2 years old I believe, but only for the last 3 months as a realm.

**Comment by Desterly** [comment] 2021-11-03 20:22
Gotcha... Thanks for confirming.
It's interesting because there are chunk records in the database that really shouldn't be there... it almost looks as if the database was upgraded (or partially upgraded) then failed so it retained the old chunk info as well as the new...   

It could also be where/how the world was originally created (on a console I'm guessing) as there are a few references to "legacy_console_player" which I've never ran across before.

Regardless, I'll put a fix up for the main issue but it's a great database for some other lingering items I've ran across..

@cabbey can expect a few more PR's soon :D

**Comment by Dev252323** [comment] 2021-11-03 21:19
It really is interesting getting this information of a world in which we have played for such a long time, this world has already pass trough a lot.

Its probable that it was created on Xbox One but I'm not sure.  Maybe even before the Better Together Update. (Maybe that could explain some things)

The age did not seem to stop me from using your software to make a map of the world the first time even though there was some strange things on it back then.

**I really glad this was helpful.** Seeing that my long lasting journey is so intriguing in a more technical manner.

**Comment by cabbey** [comment] 2021-11-10 06:47
@Desterly are you on the discord server by any chance?

**Comment by Desterly** [comment] 2021-11-10 13:22
@cabbey I am now.  (I have to admit, I was looking for "discord" in the readme and never noticed it in the header.... heh)

**Comment by cabbey** [comment] 2021-11-20 02:31
This should be resolved with v0.1.6 now available. Please reopen with notes if this specific problem is still happening.

**Closed by cabbey** 2021-11-20 02:31 UTC
Labels: bug
